-- PostgreSQL 16+ 신규 구축용. 기존 SQLite 데이터 이전 스크립트가 아닙니다.
BEGIN;
CREATE SCHEMA cs_chatbot;
SET LOCAL search_path TO cs_chatbot, public;

CREATE TABLE customer (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name TEXT NOT NULL,
 phone TEXT,
 email TEXT,
 privacy_agreed BOOLEAN NOT NULL DEFAULT FALSE,
 privacy_agreed_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE admin_user (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 login_id TEXT NOT NULL UNIQUE,
 password_hash TEXT NOT NULL,
 name TEXT NOT NULL,
 is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE product (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_name TEXT NOT NULL,
 description TEXT,
 category TEXT,
 brand TEXT,
 price BIGINT NOT NULL CHECK (price >= 0),
 stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
 status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','SOLD_OUT','DISCONTINUED')),
 is_event BOOLEAN NOT NULL DEFAULT FALSE,
 event_name TEXT,
 event_start_date DATE,
 event_end_date DATE,
 event_discount_rate INTEGER CHECK (event_discount_rate BETWEEN 0 AND 100),
 image_url TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 CHECK (event_end_date IS NULL OR event_start_date IS NULL OR event_end_date >= event_start_date)
);
CREATE TABLE orders (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 order_no TEXT NOT NULL UNIQUE,
 customer_id BIGINT NOT NULL REFERENCES customer(id),
 order_date TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','PAID','PREPARING','SHIPPED','DELIVERED','CANCELED')),
 total_amount BIGINT NOT NULL CHECK (total_amount >= 0),
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(id, customer_id)
);
CREATE TABLE order_item (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 order_id BIGINT NOT NULL REFERENCES orders(id),
 product_id BIGINT NOT NULL REFERENCES product(id),
 product_name TEXT NOT NULL,
 product_option TEXT,
 quantity INTEGER NOT NULL CHECK (quantity > 0),
 price BIGINT NOT NULL CHECK (price >= 0),
 discount_amount BIGINT NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
 amount BIGINT NOT NULL CHECK (amount >= 0),
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 CHECK (amount = quantity * price - discount_amount)
);
-- MVP: 주문 하나당 배송/결제 하나. 분할 배송·결제 재시도는 확장 대상.
CREATE TABLE shipping (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id),
 recipient_name TEXT NOT NULL,
 recipient_phone TEXT,
 address TEXT NOT NULL,
 delivery_city TEXT,
 delivery_country TEXT NOT NULL DEFAULT 'KR',
 shipping_method TEXT,
 carrier_name TEXT,
 tracking_number TEXT,
 estimated_delivery_date DATE,
 status TEXT NOT NULL DEFAULT 'PREPARING' CHECK (status IN ('PREPARING','SHIPPING','DELIVERED','CANCELED')),
 shipped_at TIMESTAMPTZ,
 delivered_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE payment (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id),
 payment_method TEXT NOT NULL CHECK (payment_method IN ('BANK_TRANSFER','CREDIT_CARD','EASY_PAY')),
 payment_status TEXT NOT NULL DEFAULT 'PENDING' CHECK (payment_status IN ('PENDING','COMPLETED','FAILED','CANCELED','REFUNDED')),
 amount BIGINT NOT NULL CHECK (amount >= 0),
 transaction_id TEXT UNIQUE,
 paid_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE refund (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id),
 refund_reason TEXT NOT NULL,
 refund_amount BIGINT NOT NULL CHECK (refund_amount > 0),
 refund_status TEXT NOT NULL DEFAULT 'REQUESTED' CHECK (refund_status IN ('REQUESTED','PROCESSING','COMPLETED','REJECTED')),
 requested_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 processed_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE conversation (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 customer_id BIGINT NOT NULL REFERENCES customer(id),
 title TEXT,
 status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','CLOSED')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 closed_at TIMESTAMPTZ,
 UNIQUE(id, customer_id)
);
-- inquiry 1행 = 고객 메시지 1개. conversation 하나에 여러 inquiry.
CREATE TABLE inquiry (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 inquiry_no TEXT NOT NULL UNIQUE,
 conversation_id BIGINT NOT NULL,
 customer_id BIGINT NOT NULL REFERENCES customer(id),
 order_id BIGINT,
 content TEXT NOT NULL CHECK (length(trim(content)) > 0),
 detected_language TEXT NOT NULL DEFAULT 'unknown',
 status TEXT NOT NULL DEFAULT 'RECEIVED' CHECK (status IN ('RECEIVED','PROCESSING','REVIEW_PENDING','AUTO_ANSWERED','COMPLETED','FAILED')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 FOREIGN KEY (conversation_id, customer_id) REFERENCES conversation(id, customer_id),
 FOREIGN KEY (order_id, customer_id) REFERENCES orders(id, customer_id)
);
CREATE TABLE ai_analysis (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 inquiry_id BIGINT NOT NULL REFERENCES inquiry(id),
 category TEXT NOT NULL,
 intent TEXT NOT NULL,
 category_confidence NUMERIC(6,5) CHECK (category_confidence BETWEEN 0 AND 1),
 intent_confidence NUMERIC(6,5) CHECK (intent_confidence BETWEEN 0 AND 1),
 urgency TEXT NOT NULL DEFAULT 'NORMAL' CHECK (urgency IN ('NORMAL','CAUTION','URGENT')),
 urgency_confidence NUMERIC(6,5) CHECK (urgency_confidence BETWEEN 0 AND 1),
 auto_response_allowed BOOLEAN NOT NULL DEFAULT FALSE,
 decision_reason TEXT,
 decision_rule_version TEXT NOT NULL,
 analysis_model TEXT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(id, inquiry_id)
);
-- 정책 버전별 새 행. 기존 정책/청크를 수정하지 않아야 과거 근거가 보존됩니다.
CREATE TABLE policy_document (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 document_key TEXT NOT NULL,
 title TEXT NOT NULL,
 category TEXT,
 content TEXT NOT NULL,
 source_file TEXT,
 version TEXT NOT NULL,
 is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(document_key, version)
);
CREATE UNIQUE INDEX uq_policy_active ON policy_document(document_key) WHERE is_active;
CREATE TABLE policy_chunk (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 policy_document_id BIGINT NOT NULL REFERENCES policy_document(id),
 chunk_text TEXT NOT NULL,
 chunk_order INTEGER NOT NULL CHECK (chunk_order >= 0),
 category TEXT,
 section TEXT,
 page_number INTEGER CHECK (page_number > 0),
 embedding_id TEXT,
 vector_collection TEXT,
 embedding_model TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(policy_document_id, chunk_order),
 UNIQUE(vector_collection, embedding_id)
);
CREATE TABLE ai_response (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 inquiry_id BIGINT NOT NULL REFERENCES inquiry(id),
 analysis_id BIGINT NOT NULL,
 response_text TEXT NOT NULL CHECK (length(btrim(response_text)) > 0),
 response_language TEXT NOT NULL,
 generation_model TEXT NOT NULL,
 adapter_version TEXT,
 prompt_version TEXT NOT NULL,
 -- LLM이 만든 원문은 response_text, 전송할 최종 문구는 final_response_text.
 final_response_text TEXT,
 status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','REVIEW_PENDING','APPROVED','REJECTED','SENT')),
 sent_automatically BOOLEAN NOT NULL DEFAULT FALSE,
 sent_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 FOREIGN KEY (analysis_id, inquiry_id) REFERENCES ai_analysis(id, inquiry_id),
 CHECK ((status = 'SENT' AND sent_at IS NOT NULL AND final_response_text IS NOT NULL AND length(trim(final_response_text)) > 0)
     OR (status <> 'SENT' AND sent_at IS NULL AND NOT sent_automatically))
);
CREATE UNIQUE INDEX uq_sent_response ON ai_response(inquiry_id) WHERE status = 'SENT';
CREATE TABLE retrieved_policy (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 response_id BIGINT NOT NULL REFERENCES ai_response(id),
 policy_chunk_id BIGINT NOT NULL REFERENCES policy_chunk(id),
 similarity_score DOUBLE PRECISION,
 score_metric TEXT NOT NULL,
 rank INTEGER NOT NULL CHECK (rank > 0),
 used_in_prompt BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(response_id, rank),
 UNIQUE(response_id, policy_chunk_id)
);
CREATE TABLE admin_review (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 response_id BIGINT NOT NULL REFERENCES ai_response(id),
 admin_id BIGINT NOT NULL REFERENCES admin_user(id),
 original_category TEXT NOT NULL,
 modified_category TEXT NOT NULL,
 original_intent TEXT NOT NULL,
 modified_intent TEXT NOT NULL,
 original_urgency TEXT NOT NULL CHECK (original_urgency IN ('NORMAL','CAUTION','URGENT')),
 modified_urgency TEXT NOT NULL CHECK (modified_urgency IN ('NORMAL','CAUTION','URGENT')),
 original_response TEXT NOT NULL,
 modified_response TEXT NOT NULL CHECK (length(btrim(modified_response)) > 0),
 approved BOOLEAN NOT NULL,
 use_for_training BOOLEAN NOT NULL DEFAULT FALSE,
 reviewed_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 remark TEXT
);
-- feedback는 실제 전송된 답변에만 작성합니다.
CREATE TABLE feedback (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 response_id BIGINT NOT NULL UNIQUE REFERENCES ai_response(id),
 rating TEXT NOT NULL CHECK (rating IN ('SATISFIED','DISSATISFIED')),
 comment TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX ix_orders_customer ON orders(customer_id, order_date);
CREATE INDEX ix_order_item_order ON order_item(order_id);
CREATE INDEX ix_order_item_product ON order_item(product_id);
CREATE INDEX ix_conversation_customer ON conversation(customer_id, created_at);
CREATE INDEX ix_inquiry_conversation ON inquiry(conversation_id, created_at, id);
CREATE INDEX ix_inquiry_customer ON inquiry(customer_id);
CREATE INDEX ix_inquiry_order ON inquiry(order_id);
CREATE INDEX ix_inquiry_queue ON inquiry(status, created_at);
CREATE INDEX ix_analysis_inquiry ON ai_analysis(inquiry_id, id);
CREATE INDEX ix_response_inquiry ON ai_response(inquiry_id, id);
CREATE INDEX ix_review_response ON admin_review(response_id, id);
CREATE INDEX ix_review_admin ON admin_review(admin_id);
CREATE INDEX ix_retrieved_chunk ON retrieved_policy(policy_chunk_id);

-- 모든 함수는 대상 스키마를 고정합니다.
CREATE FUNCTION touch_updated_at() RETURNS trigger
LANGUAGE plpgsql SET search_path = cs_chatbot, pg_temp AS $$
BEGIN NEW.updated_at := clock_timestamp(); RETURN NEW; END;
$$;
DO $$
DECLARE t text;
BEGIN
 FOREACH t IN ARRAY ARRAY['customer','product','orders','shipping','payment','inquiry','ai_response'] LOOP
  EXECUTE format('CREATE TRIGGER z_touch_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION touch_updated_at()',t);
 END LOOP;
END;
$$;

CREATE FUNCTION immutable_row() RETURNS trigger
LANGUAGE plpgsql SET search_path = cs_chatbot, pg_temp AS $$
BEGIN RAISE EXCEPTION 'Historical row in % is immutable; insert a new version', TG_TABLE_NAME USING ERRCODE='23514'; END;
$$;
CREATE TRIGGER analysis_immutable BEFORE UPDATE OR DELETE ON ai_analysis FOR EACH ROW EXECUTE FUNCTION immutable_row();
CREATE TRIGGER review_immutable BEFORE UPDATE OR DELETE ON admin_review FOR EACH ROW EXECUTE FUNCTION immutable_row();
CREATE TRIGGER chunk_immutable BEFORE UPDATE OR DELETE ON policy_chunk FOR EACH ROW EXECUTE FUNCTION immutable_row();

CREATE FUNCTION guard_policy_document() RETURNS trigger
LANGUAGE plpgsql SET search_path = cs_chatbot, pg_temp AS $$
BEGIN
 IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Policy versions cannot be deleted' USING ERRCODE='23514'; END IF;
 IF (to_jsonb(NEW) - 'is_active') IS DISTINCT FROM (to_jsonb(OLD) - 'is_active') THEN
  RAISE EXCEPTION 'Insert a new policy version; only is_active may change' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER policy_immutable BEFORE UPDATE OR DELETE ON policy_document FOR EACH ROW EXECUTE FUNCTION guard_policy_document();

CREATE FUNCTION guard_review() RETURNS trigger
LANGUAGE plpgsql SET search_path = cs_chatbot, pg_temp AS $$
DECLARE r ai_response%ROWTYPE; a ai_analysis%ROWTYPE;
BEGIN
 -- 같은 답변의 검토와 전송은 행 잠금으로 직렬화합니다.
 SELECT * INTO r FROM ai_response WHERE id=NEW.response_id FOR UPDATE;
 IF NOT FOUND OR r.status='SENT' THEN
  RAISE EXCEPTION 'Review requires an existing unsent response' USING ERRCODE='23514';
 END IF;
 IF NOT EXISTS (SELECT 1 FROM admin_user WHERE id=NEW.admin_id AND is_active) THEN
  RAISE EXCEPTION 'Reviewer must be active' USING ERRCODE='23514';
 END IF;
 SELECT * INTO a FROM ai_analysis WHERE id=r.analysis_id;
 IF NEW.original_response IS DISTINCT FROM r.response_text
 OR NEW.original_category IS DISTINCT FROM a.category
 OR NEW.original_intent IS DISTINCT FROM a.intent
 OR NEW.original_urgency IS DISTINCT FROM a.urgency THEN
  RAISE EXCEPTION 'Original review fields must match the AI snapshot' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER review_before_send BEFORE INSERT ON admin_review FOR EACH ROW EXECUTE FUNCTION guard_review();

CREATE FUNCTION guard_response() RETURNS trigger
LANGUAGE plpgsql SET search_path = cs_chatbot, pg_temp AS $$
DECLARE v_review admin_review%ROWTYPE;
BEGIN
 IF TG_OP='DELETE' THEN
  IF OLD.status='SENT' THEN RAISE EXCEPTION 'Sent response is immutable' USING ERRCODE='23514'; END IF;
  RETURN OLD;
 END IF;
 IF TG_OP='UPDATE' THEN
  IF OLD.status='SENT' THEN RAISE EXCEPTION 'Sent response is immutable' USING ERRCODE='23514'; END IF;
  IF ROW(NEW.inquiry_id,NEW.analysis_id,NEW.response_text,NEW.response_language,NEW.generation_model,NEW.adapter_version,NEW.prompt_version)
    IS DISTINCT FROM ROW(OLD.inquiry_id,OLD.analysis_id,OLD.response_text,OLD.response_language,OLD.generation_model,OLD.adapter_version,OLD.prompt_version) THEN
   RAISE EXCEPTION 'Keep the original AI response; insert a new response to regenerate' USING ERRCODE='23514';
  END IF;
 END IF;
 IF NEW.status='SENT' THEN
  IF NEW.sent_automatically THEN
   IF NOT EXISTS (SELECT 1 FROM ai_analysis WHERE id=NEW.analysis_id AND auto_response_allowed) THEN
    RAISE EXCEPTION 'Automatic response not allowed' USING ERRCODE='23514';
   END IF;
   IF NEW.final_response_text IS DISTINCT FROM NEW.response_text THEN
    RAISE EXCEPTION 'Automatic final text must match the generated text' USING ERRCODE='23514';
   END IF;
   IF EXISTS (SELECT 1 FROM admin_review WHERE response_id=NEW.id) THEN
    RAISE EXCEPTION 'Reviewed responses must use manual sending' USING ERRCODE='23514';
   END IF;
  ELSE
   SELECT * INTO v_review FROM admin_review WHERE response_id=NEW.id ORDER BY id DESC LIMIT 1;
   IF NOT FOUND OR NOT v_review.approved OR v_review.modified_response IS DISTINCT FROM NEW.final_response_text THEN
    RAISE EXCEPTION 'Latest review must approve the exact final text' USING ERRCODE='23514';
   END IF;
  END IF;
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER response_guard BEFORE INSERT OR UPDATE OR DELETE ON ai_response FOR EACH ROW EXECUTE FUNCTION guard_response();

CREATE FUNCTION sync_sent_inquiry() RETURNS trigger
LANGUAGE plpgsql SET search_path = cs_chatbot, pg_temp AS $$
BEGIN
 IF NEW.status='SENT' THEN
  UPDATE inquiry SET status=CASE WHEN NEW.sent_automatically THEN 'AUTO_ANSWERED' ELSE 'COMPLETED' END WHERE id=NEW.inquiry_id;
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER response_sync AFTER INSERT OR UPDATE ON ai_response FOR EACH ROW EXECUTE FUNCTION sync_sent_inquiry();

CREATE FUNCTION guard_feedback() RETURNS trigger
LANGUAGE plpgsql SET search_path = cs_chatbot, pg_temp AS $$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM ai_response WHERE id=NEW.response_id AND status='SENT') THEN
  RAISE EXCEPTION 'Feedback requires a sent response' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER feedback_guard BEFORE INSERT OR UPDATE ON feedback FOR EACH ROW EXECUTE FUNCTION guard_feedback();

CREATE VIEW chat_history AS
 SELECT q.conversation_id,q.customer_id,q.id AS inquiry_id,
 'user'::text AS role,q.content,q.created_at AS occurred_at,
 0 AS event_order,q.id AS event_id
 FROM inquiry q
 UNION ALL
 SELECT q.conversation_id,q.customer_id,q.id,
 'assistant',r.final_response_text,r.sent_at,1,r.id
 FROM ai_response r JOIN inquiry q ON q.id=r.inquiry_id
 WHERE r.status='SENT';

COMMENT ON TABLE customer IS '고객. customer는 올바른 영어 철자이며 costumer(의상 담당자)와 다릅니다.';
COMMENT ON TABLE inquiry IS '고객 문의 메시지 한 건. 같은 대화방에 여러 건 저장합니다.';
COMMENT ON COLUMN ai_response.adapter_version IS '파인튜닝 Adapter의 버전 또는 추적 가능한 식별자';
COMMENT ON COLUMN admin_review.original_response IS '검토 이전 수정본이 아닌 해당 AI 답변의 불변 생성 원문';
COMMENT ON COLUMN retrieved_policy.similarity_score IS '점수 범위와 방향은 score_metric에 따라 다릅니다. 확률이 아닙니다.';
COMMIT;
