"""daitda screens

Revision ID: 3f9589e9fdcb
Revises: 
Create Date: 2026-10-02 14:52:52.010845

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3f9589e9fdcb'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_key', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_document_doc_key'), ['doc_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_document_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquiry_no', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='conversationstatus', native_enum=False, length=30), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('last_answer_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.Enum('USER', 'NEW_CHAT', 'TIMEOUT', 'ADMIN_ANSWERED', name='closereason', native_enum=False, length=30), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_inquiry_no'), ['inquiry_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_conversation_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_status'), ['status'], unique=False)

    op.create_table('local_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    with op.batch_alter_table('local_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_order_customer_id'), ['customer_id'], unique=False)

    op.create_table('policy_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_document_id'], ['policy_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_chunk_policy_document_id'), ['policy_document_id'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'BOT', 'ADMIN', name='messagerole', native_enum=False, length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('is_notice', sa.Boolean(), nullable=False),
    sa.Column('question_status', sa.Enum('PROCESSING', 'AUTO_ANSWERED', 'REVIEW_PENDING', 'ADMIN_ANSWERED', name='questionstatus', native_enum=False, length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_question_status'), ['question_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reply_to_id'), ['reply_to_id'], unique=False)

    op.create_table('admin_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('original_category', sa.String(length=30), nullable=True),
    sa.Column('modified_category', sa.String(length=30), nullable=False),
    sa.Column('original_intent', sa.String(length=50), nullable=True),
    sa.Column('modified_intent', sa.String(length=50), nullable=False),
    sa.Column('original_response', sa.Text(), nullable=True),
    sa.Column('modified_response', sa.Text(), nullable=False),
    sa.Column('use_for_training', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_user.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('ai_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('intent_confidence', sa.Float(), nullable=True),
    sa.Column('auto_response_allowed', sa.Boolean(), nullable=False),
    sa.Column('decision_reasons', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('analysis_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('ai_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('generation_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('sent_automatically', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('retrieved_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('policy_document_id', sa.Integer(), nullable=True),
    sa.Column('policy_chunk_id', sa.Integer(), nullable=True),
    sa.Column('document_key', sa.String(length=200), nullable=True),
    sa.Column('document_title', sa.String(length=200), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_chunk_id'], ['policy_chunk.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_document_id'], ['policy_document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retrieved_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retrieved_policy_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retrieved_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retrieved_policy_question_id'))

    op.drop_table('retrieved_policy')
    op.drop_table('ai_response')
    op.drop_table('ai_analysis')
    op.drop_table('admin_review')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_reply_to_id'))
        batch_op.drop_index(batch_op.f('ix_message_question_status'))
        batch_op.drop_index(batch_op.f('ix_message_created_at'))
        batch_op.drop_index(batch_op.f('ix_message_conversation_id'))

    op.drop_table('message')
    with op.batch_alter_table('policy_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_chunk_policy_document_id'))

    op.drop_table('policy_chunk')
    with op.batch_alter_table('local_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_order_customer_id'))

    op.drop_table('local_order')
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_status'))
        batch_op.drop_index(batch_op.f('ix_conversation_is_demo'))
        batch_op.drop_index(batch_op.f('ix_conversation_inquiry_no'))
        batch_op.drop_index(batch_op.f('ix_conversation_customer_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_created_at'))
        batch_op.drop_index(batch_op.f('ix_conversation_category'))

    op.drop_table('conversation')
    with op.batch_alter_table('policy_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_document_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_policy_document_doc_key'))

    op.drop_table('policy_document')
    op.drop_table('customer')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
